import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const projects=JSON.parse(readFileSync(resolve(root,'projects.json'),'utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=[['index.html','Home'],['portfolio.html','Portfolio'],['about.html','About'],['resume.html','Resume'],['contact.html','Contact']];
const email='brianbays@hotmail.com';
const button=(href,text,secondary=false)=>`<a class="button${secondary?' secondary':''}" href="${esc(href)}">${text} <span aria-hidden="true">↗</span></a>`;
function card(p,i,detail=false){return `<article class="project ${esc(p.className)}" id="${esc(p.id)}"><a class="project-art" href="${detail?(p.url?esc(p.url):'contact.html'):'portfolio.html#'+esc(p.id)}" aria-label="${esc(detail?(p.url?p.linkLabel:'Ask about '+p.title):'Explore '+p.title)}">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.title)} project artwork" loading="lazy" width="1200" height="750">`:''}<div class="art-label"><span class="eyebrow">${esc(p.category)}</span><span class="art-title">${esc(p.title)}</span><span class="art-credit">A project by Brian Bays</span></div><span class="art-arrow" aria-hidden="true">↗</span></a><div class="project-meta"><div><p class="eyebrow">0${i+1} / ${esc(p.role)}</p><h${detail?'2':'3'}>${esc(p.title)}</h${detail?'2':'3'}></div>${!detail?'<span aria-hidden="true">↗</span>':''}</div>${detail?`<p class="project-description">${esc(p.description)}</p>${button(p.url||'mailto:'+email+'?subject='+encodeURIComponent(p.title+' — portfolio inquiry'),p.url?p.linkLabel:'Ask about this project',true)}`:''}</article>`;}
const cta=`<section class="cta"><p class="eyebrow">Have a project in mind?</p><div><h2>Let’s make something<br><em>worth watching.</em></h2>${button('contact.html','Get in touch')}</div></section>`;
const pages={
'index.html':{title:'Brian Bays — Creative Producer, Editor & Filmmaker',description:'Film, trailers, and editorial work by Brian Bays. Creative producer, editor, filmmaker, and post-production leader based in Southern California.',body:`<section class="hero"><p class="eyebrow"><span class="dot"></span> Brian Bays / Southern California</p><h1>Every story.<br><em>Every frame.</em></h1><div class="hero-bottom"><p>Creative Producer · Editor · Filmmaker<br>Post-Production Leader</p>${button('portfolio.html','Explore my work')}</div><span class="hero-index" aria-hidden="true">BB / 01</span></section><section class="work"><div class="section-heading"><h2>Selected work</h2><a href="portfolio.html">View portfolio <span aria-hidden="true">↗</span></a></div><div class="project-grid">${projects.slice(0,2).map((p,i)=>card(p,i)).join('')}</div></section><section class="intro"><p class="eyebrow">Creative instincts. Production experience.</p><div><h2>From the first idea<br>to the final delivery.</h2><p>I’m Brian, a filmmaker and editor with more than 22 years in post-production. I bring a storyteller’s eye and a technical problem solver’s approach to the work.</p><a class="text-link" href="about.html">More about me <span aria-hidden="true">↗</span></a></div></section>${cta}`},
'portfolio.html':{title:'Portfolio — Brian Bays',description:'Explore Head Games, The Evil in Me, and short-form editing work by Brian Bays.',body:`<section class="page-head"><p class="eyebrow">Film / Trailers / Editorial</p><h1>Selected <em>work.</em></h1><p>Original stories, cinematic edits, and a feel for the moment.</p></section><section class="project-grid portfolio-grid" aria-label="Projects">${projects.map((p,i)=>card(p,i,true)).join('')}</section>${cta}`},
'about.html':{title:'About — Brian Bays',description:'Meet Brian Bays: filmmaker, editor, and post-production leader with an MFA in Film Production and over 22 years of experience.',body:`<section class="page-head"><p class="eyebrow">About Brian</p><h1>A storyteller.<br><em>A problem solver.</em></h1></section><section class="about-layout"><div class="monogram" aria-hidden="true"><span>BRIAN<br>BAYS<span class="small">FILM / EDITORIAL / POST</span></span></div><div class="prose"><p class="lead">I’m a Southern California filmmaker and editor who understands both the creative work and what it takes to deliver it.</p><p>My background brings together an MFA in Film Production from Ohio University, a BA in Telecommunications and Film Studies from Purdue University, and more than 22 years in post-production at Deluxe Digital Studios.</p><p>At Deluxe, I led global authoring teams, solved complex production challenges, and helped deliver entertainment for Disney, Paramount, Warner Bros., and Universal. I also developed tools and workflows that saved hundreds of hours across departments.</p><p>My creative work includes <cite>Head Games</cite>, <cite>The Evil in Me</cite>, and short-form editing. I’m drawn to the relationship between story, sound, and pacing—and to new ways of bringing an idea to the screen.</p><p>Outside the edit, I’m a guitarist and podcast enthusiast.</p>${button('resume.html','View my experience',true)}</div></section>${cta}`},
'resume.html':{title:'Resume — Brian Bays',description:'Brian Bays: professional experience, education, post-production leadership, and creative skills.',body:`<section class="page-head"><p class="eyebrow">Experience / Education / Skills</p><h1>Creative thinking.<br><em>Proven delivery.</em></h1><div class="actions">${button('files/Brian_Bays_Resume.pdf','Download resume (PDF)')}<button class="button secondary" id="print-resume" type="button">Print this page</button></div></section><div class="resume-layout"><aside><h2>Brian Bays</h2><p>Canyon Country, California</p><a href="mailto:${email}">${email}</a><h3>Core strengths</h3><ul class="plain-list"><li>Video editing</li><li>Digital media production</li><li>Project management & scheduling</li><li>Team leadership & mentoring</li><li>Workflow optimization</li><li>Technical problem solving</li><li>Client & vendor relations</li><li>Global resource coordination</li></ul><h3>Editing & authoring</h3><p>Adobe Premiere Pro<br>Scenarist DVD Authoring<br>Panasonic DVD Authoring</p></aside><section class="prose resume-main"><h2>Profile</h2><p>Collaborative media professional with more than 22 years of experience in post-production, complex digital workflows, and team leadership. A creative and technical background, with a record of delivering under pressure and streamlining production.</p><h2>Professional experience</h2><h3>Deluxe Digital Studios</h3><p class="muted">Burbank, California</p><div class="role"><strong>DVD Authoring Manager</strong><span>2009–2025</span></div><div class="role"><strong>DVD Author / Software Engineer</strong><span>2002–2009</span></div><ul><li>Delivered high-volume DVD authoring and post-production for Disney, Paramount, Warner Bros., Universal, and other studio clients.</li><li>Led and mentored global teams across Burbank, India, Malaysia, London, Canada, New York, and Pennsylvania.</li><li>Developed programming templates, specifications, and streamlined workflows for worldwide commercial releases.</li><li>Managed troubleshooting, client escalations, and last-minute revisions while meeting aggressive deadlines.</li><li>Received multiple Great Performer Awards for tools that saved hundreds of hours across departments.</li><li>Collaborated with Scenarist on version 5, released in 2020, including multi-angle branching capabilities.</li></ul><h2>Education</h2><h3>Master of Fine Arts · Film Production</h3><p>Ohio University · Athens, Ohio</p><h3>Bachelor of Arts · Telecommunications and Film Studies</h3><p>Purdue University · West Lafayette, Indiana</p><h2>Creative work</h2><p><a href="portfolio.html#head-games">Head Games</a> · <a href="portfolio.html#evil-in-me">The Evil in Me</a> · <a href="portfolio.html#short-form">Short-form & social</a></p></section></div>`},
'contact.html':{title:'Contact — Brian Bays',description:'Contact Brian Bays about editing, filmmaking, creative production, and post-production opportunities.',body:`<section class="page-head contact-head"><p class="eyebrow">Contact</p><h1>Good work starts<br><em>with a conversation.</em></h1><p>For editing, filmmaking, and creative production opportunities, I’d love to hear what you have in mind.</p><a class="email-link" href="mailto:${email}">${email}<span aria-hidden="true">↗</span></a><div class="contact-details"><div><p class="eyebrow">Based in</p><p>Southern California</p></div><div><p class="eyebrow">Explore</p><a href="portfolio.html">View my work ↗</a><br><a href="files/Brian_Bays_Resume.pdf">Download resume ↗</a></div></div></section>`}
};
for(const [file,p] of Object.entries(pages)) writeFileSync(resolve(root,'site',file),`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#171916"><title>${esc(p.title)}</title><meta name="description" content="${esc(p.description)}"><meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><meta property="og:type" content="website"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css"><script src="assets/main.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="index.html" aria-label="Brian Bays home">BRIAN BAYS<span class="brand-dot">.</span></a><nav aria-label="Main navigation">${nav.map(([url,label])=>`<a href="${url}"${url===file?' aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main">${p.body}</main><footer><a class="brand" href="index.html">BRIAN BAYS<span class="brand-dot">.</span></a><p>Film. Editorial. Post-production.</p><p>© ${new Date().getFullYear()} Brian Bays</p></footer></body></html>`);
writeFileSync(resolve(root,'site','404.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found — Brian Bays</title><link rel="stylesheet" href="/assets/style.css"></head><body><main class="page-head"><p class="eyebrow">404 / Page not found</p><h1>Back to <em>the story.</em></h1><a class="button" href="/">Go to the homepage ↗</a></main></body></html>`);
writeFileSync(resolve(root,'site','.nojekyll'),'');
console.log('Built five pages and a 404 page.');
